version: 2.0
jobs:
  build:
    docker:
        - image: burgerdev/ocaml-addressmapper-devel:0.1-ubuntu
    working_directory: /tmp/oam
    steps:
      - checkout
      - run:
          name: "Build"
          command: |
            eval `opam config env`
            make build
      - run:
          name: "Test"
          command: |
            eval `opam config env`
            make test
      - store_artifacts:
          path: /tmp/oam/_build/src/main.native
          destination: address-mapper
