version: 2.0
jobs:
  build:
    docker:
      - image: burgerdev/ocaml-addressmapper-devel:0.3-alpine
    steps:
      - checkout
      - run:
          name: "Build"
          command: |
            eval `opam config env`
            make build
      - run:
          name: "Test"
          command: |
            eval `opam config env`
            make test
