version: 2.0
jobs:
  build:
    docker:
    - image: ocaml/opam2:alpine-3.8-ocaml-4.06
    working_directory: /tmp/mapper
    steps:
    - run:
        name: "conf-deps"
        command: sudo apk add --no-cache m4 ncurses
    - checkout
    - run:
        name: "fetch_deps"
        command: make fetch_deps
    - run:
        name: "build"
        command: make
    - run:
        name: "test"
        command: make test
workflows:
  version: 2
  push_validation:
    jobs:
      - build
