FROM alpine

LABEL org.label-schema.vcs-ref=HASH \
      org.label-schema.vcs-url="https://github.com/burgerdev/ocaml-addressmapper"

ADD URL /main.native
RUN chmod a+x /main.native

ENTRYPOINT ["/main.native"]

EXPOSE 30303
